quarkus.http.port=${HTTP_PORT:8081}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5432/sdd}
quarkus.datasource.username=${DB_USERNAME:admin}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.hibernate-orm.schema-management.strategy=${DB_SCHEMA_GENERATION:update}
quarkus.hibernate-orm.log.sql=false
quarkus.smallrye-health.root-path=/q/health
quarkus.rest.exception-mapping.disable-mapper-for=io.quarkus.resteasy.reactive.jackson.runtime.mappers.BuiltinMismatchedInputExceptionMapper

%dev.quarkus.hibernate-orm.schema-management.strategy=update
%docker.quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://postgres:5432/sdd}
%docker.quarkus.datasource.username=${DB_USERNAME:admin}
%docker.quarkus.datasource.password=${DB_PASSWORD}
%docker.quarkus.hibernate-orm.schema-management.strategy=update
%kubernetes.quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://postgresql:5432/sdd}
%kubernetes.quarkus.datasource.username=${DB_USERNAME:admin}
%kubernetes.quarkus.datasource.password=${DB_PASSWORD}
%kubernetes.quarkus.hibernate-orm.schema-management.strategy=update
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:users;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
