quarkus.http.port=${HTTP_PORT:8080}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5432/sdd}
quarkus.datasource.username=${DB_USERNAME:admin}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.hibernate-orm.database.generation=${DB_SCHEMA_GENERATION:validate}
quarkus.hibernate-orm.log.sql=false

%dev.quarkus.hibernate-orm.database.generation=update
%docker.quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://postgres:5432/sdd}
%docker.quarkus.datasource.username=${DB_USERNAME:admin}
%docker.quarkus.datasource.password=${DB_PASSWORD}
%docker.quarkus.hibernate-orm.database.generation=update
%kubernetes.quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://postgresql:5432/sdd}
%kubernetes.quarkus.datasource.username=${DB_USERNAME:admin}
%kubernetes.quarkus.datasource.password=${DB_PASSWORD}
%kubernetes.quarkus.hibernate-orm.database.generation=update
