apiVersion: apps/v1
kind: Deployment
metadata:
  name: empresa
  namespace: sdd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empresa
  template:
    metadata:
      labels:
        app: empresa
    spec:
      containers:
        - name: empresa
          image: empresa:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: empresa-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8081
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8081
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
